# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Kevin ALBESSARD, développeur web et mobile"
email: "k.albessard@gmail.com"
description: "Spécialisé dans le développement front-end, je réalise des interfaces avec les dernières technologies Web pour une expérience utilisateur toujours plus simple et ergonomique."
baseurl: ""
url: ""
permalink: "pretty"


# Build settings
markdown: kramdown
exclude: ["gulpfile.js",
          "node_modules",
          "package.json"]